Vagrant.configure("2") do |config|
	config.vm.box = "peru/ubuntu-20.04-server-amd64"
	config.disksize.size = '50GB'
	#config.vm.network "private_network", ip: "192.168.33.15"

	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "playbook.yml"
	end
end